import React, { ReactNode, useState, useEffect } from 'react';
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  BackgroundVariant,
  Node,
  Edge,
  OnNodesChange,
  OnEdgesChange,
  OnConnect,
  OnInit,
  NodeTypes,
  ReactFlowInstance,
  MarkerType
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { Button } from '@/components/ui/button';
import ResetGraphButton from './ResetGraphButton';
import { Layout, FileText, LogIn, LogOut, User2, Github } from 'lucide-react';
import { cn } from '@/lib/utils';
import { supabase } from '@/lib/supabaseClient';
import { useNavigate } from 'react-router-dom';
import { toast } from "@/components/ui/sonner";
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from '@/components/ui/tooltip';

interface TechStackFlowProps {
  nodes: Node[];
  edges: Edge[];
  onNodesChange: OnNodesChange;
  onEdgesChange: OnEdgesChange;
  onConnect: OnConnect;
  onInit: OnInit<any>;
  onDrop: React.DragEventHandler<HTMLDivElement>;
  onDragOver: React.DragEventHandler<HTMLDivElement>;
  nodeTypes: NodeTypes;
  onSave: () => void;
  onReset: () => void;
  onAutoLayout: () => void;
  onOpenDocs: () => void;
  isSidebarCollapsed: boolean;
}

const TechStackFlow: React.FC<TechStackFlowProps> = ({ 
  nodes,
  edges,
  onNodesChange,
  onEdgesChange,
  onConnect,
  onInit,
  onDrop,
  onDragOver,
  nodeTypes,
  onSave, 
  onReset,
  onAutoLayout,
  onOpenDocs,
  isSidebarCollapsed
}) => {
  const navigate = useNavigate();
  const [session, setSession] = useState<any>(null);
  const [githubUser, setGithubUser] = useState<any>(null);

  useEffect(() => {
    const fetchGithubUser = async () => {
      try {
        const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:5001'}/api/github/user`, {
          credentials: 'include'
        });
        if (response.ok) {
          const userData = await response.json();
          setGithubUser(userData);
          console.log("DEBUG: GitHub user data fetched:", userData);
        } else if (response.status === 401) {
          setGithubUser(null);
          console.log("DEBUG: Not authenticated with GitHub (401).");
        } else {
          console.error("Failed to fetch GitHub user:", await response.text());
          setGithubUser(null);
        }
      } catch (error) {
        console.error("Error fetching GitHub user:", error);
        setGithubUser(null);
      }
    };

    if (session) {
      fetchGithubUser();
    } else {
      setGithubUser(null);
    }
  }, [session]);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
    });

    const { data: authListener } = supabase.auth.onAuthStateChange(
      (event, session) => {
        setSession(session);
      }
    );

    return () => {
      authListener.subscription.unsubscribe();
    };
  }, [navigate]);

  const handleSave = () => {
    onSave();
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
  };

  const handleLogin = () => {
    navigate('/auth');
  };

  const handleCreateGitHubRepo = async () => {
    if (!session) {
      toast.info("Please log in to your Stackwise account first to use GitHub integration.");
      handleLogin();
      return;
    }

    if (!githubUser) {
      window.location.href = `${import.meta.env.VITE_API_URL || 'http://localhost:5001'}/api/github/login`;
      return;
    }

    const repoName = prompt("Enter the desired GitHub repository name:");
    if (!repoName || repoName.trim() === '') {
      toast.info("Repository creation cancelled.");
      return;
    }

    const confirmPrivate = confirm("Make this repository private? (Cancel for public)");
    const isPrivate = confirmPrivate;

    toast.loading(`Creating GitHub repository '${repoName}'...`, { id: "createRepoToast" });
    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:5001'}/api/github/create_repository`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include',
        body: JSON.stringify({
          name: repoName.trim(),
          description: "Tech stack graph generated by Stackwise",
          private: isPrivate,
        }),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.message || "Failed to create repository");
      }

      toast.success(`Repository '${repoName}' created successfully!`, { id: "createRepoToast", duration: 5000 });
      console.log("GitHub Repository Created:", result);

    } catch (error: any) {
      console.error("Error creating GitHub repository:", error);
      toast.error(`Failed to create repository: ${error.message}`, { id: "createRepoToast", duration: 5000 });
    }
  };

  return (
    <div className="h-full w-full flex flex-col">
      <div className="flex justify-between items-center p-2 bg-background border-b">
        <h2 className="px-2 text-lg font-medium flex items-center">
          <img 
            src="/stackwiseLogo.png"
            alt="Stackwise logo" 
            className="h-5 w-5 mr-2"
          /> 
          <span>stackwise</span>
        </h2>
        <div className="flex gap-2">
          <Button
            onClick={handleSave}
            variant="outline"
            size="sm"
          >
            Save Graph
          </Button>
          <ResetGraphButton onReset={onReset} size="sm" />
          <Button
            onClick={onAutoLayout}
            variant="outline"
            size="sm"
            title="Auto Layout"
          >
            <Layout className="h-4 w-4 mr-1" />
            Layout
          </Button>
          <Button
            onClick={onOpenDocs}
            variant="outline"
            size="sm"
            title="View Documentation"
          >
            <FileText className="h-4 w-4 mr-1" />
            Docs
          </Button>
          {session && (
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    onClick={handleCreateGitHubRepo}
                    variant="outline"
                    size="sm"
                    title={githubUser ? `Create GitHub Repo as ${githubUser.login}` : "Connect to GitHub"}
                    className="bg-slate-700 text-white hover:bg-slate-800"
                  >
                    <Github className="h-4 w-4 mr-1" />
                    {githubUser ? "Create GitHub Repo" : "Connect GitHub"}
                  </Button>
                </TooltipTrigger>
                <TooltipContent side="bottom">
                  {githubUser
                    ? "Create a new GitHub repository and push your generated code."
                    : "Connect your GitHub account to enable repository creation and code push. This is separate from login."}
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          )}

          {session ? (
            <>
              <Button
                variant="outline"
                size="sm"
                onClick={() => { /* Placeholder for profile/dashboard navigation */ }}
                className="flex items-center gap-1"
              >
                <User2 className="h-4 w-4" />
                {session.user?.email || 'Profile'}
              </Button>
              <Button
                onClick={handleLogout}
                variant="outline"
                size="sm"
                title="Logout"
                className="bg-red-500 text-white hover:bg-red-600"
              >
                <LogOut className="h-4 w-4 mr-1" />
                Logout
              </Button>
            </>
          ) : (
            <Button
              onClick={handleLogin}
              variant="outline"
              size="sm"
              title="Login"
              className="bg-green-500 text-white hover:bg-green-600"
            >
              <LogIn className="h-4 w-4 mr-1" />
              Login
            </Button>
          )}
        </div>
      </div>
      <div className="flex-grow">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onConnect={onConnect}
          onInit={onInit}
          onDrop={onDrop}
          onDragOver={onDragOver}
          nodeTypes={nodeTypes}
          fitView
          proOptions={{ hideAttribution: true }}
          defaultEdgeOptions={{
            type: 'default',
            animated: false,
            style: { stroke: '#000000', strokeWidth: 1.5 },
            markerEnd: {
              type: MarkerType.ArrowClosed,
              width: 14,
              height: 14,
              color: '#000000',
            },
          }}
        >
          <Controls className={cn(isSidebarCollapsed && "mb-16")} />
          <MiniMap position="top-right" />
          <Background 
            variant={BackgroundVariant.Dots}
            gap={12} 
            size={1} 
          />
        </ReactFlow>
      </div>
    </div>
  );
};

export default TechStackFlow;
